#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

controller:
  # -- Number of pods to load balance between
  replicas: 1

image:
  # -- image repository
  repository: bytehow/ghidra-server
  # @default -- chart.appVersion
  tag: "10.2.2"
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC


# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      p1:
        port: 13100
        protocol: TCP
      p2:
        port: 13101
        protocol: TCP
      p3:
        port: 13102
        protocol: TCP

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false
    mountPath: /repos
