---
apiVersion: v2
appVersion: 1.26.1
description: Jellyseerr is a free and open source software application for managing requests for your media library. It integrates with your existing services such as Sonarr, Radarr and Jellyfin!
name: overseerr
version: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - overseerr
  - jellyfin
  - sonarr
  - radarr
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/jellyseerr
icon: https://i.imgur.com/TMoEG7g.png
sources:
  - https://github.com/sct/overseerr
  - https://hub.docker.com/r/fallenbagel/jellyseerr
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.4.2
