apiVersion: v1
kind: PersistentVolumeClaim
metadata:        
  name: inventree-data
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi