apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventree.fullname" . }}-app
  labels:
    {{- include "inventree.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: server
      port: {{ .Values.server.service.port }}
      targetPort: server
    - name: proxy
      port: {{ .Values.proxy.service.port }}
      targetPort: http
  selector:
    {{- include "inventree.selectorLabels" . | nindent 4 }}
