---
apiVersion: v2
appVersion: v2.1.1-1-01
description: Deluge is a torrent download client secured with a vpn
name: delugevpn
version: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - deluge
  - torrent
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/deluge
icon: https://avatars2.githubusercontent.com/u/6733935?v=3&s=200
sources:
  - https://hub.docker.com/r/linuxserver/deluge/
  - https://deluge-torrent.org/
maintainers:
  - name: mononen
    email: alex@mononen.dev
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.4.2
