apiVersion: v2
name: mononen-library-chart
description: A Helm library chart providing reusable templates for Kubernetes resources.
type: library
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - library
  - common
  - kubernetes
  - deployment
  - service
maintainers:
  - name: Alex Mononen
    email: alex@mononen.dev
    url: www.mononen.dev

